### ISSUE TITLE
Property not loading

### ISSUE THREAD

**Issue by VenomFate-619** [Ashwin1729/SweetHome#1]
https://sweet-home-real-estate.netlify.app/property/5947736
on this URL only the header coming
![image](https://user-images.githubusercontent.com/67755128/177775632-56985319-5406-410a-be6e-d41bd935cd39.png)

**Comment by Ashwin1729** [comment]
Respected Syed,
      This application is not 100% complete yet. I have implemented only
component filtration as per the requirements of my internship task so as to
submit my assignment as soon as possible. I will be implementing a full
fledged application soon and will provide a new deployment link too. Till
then stay tuned and I appreciate your concern.

Thank you,
regards,
Ashwin Dhuriya🙂

**Comment by VenomFate-619** [comment]
ok fine
